#!/bin/sh
if [ -z "$XUS_DIR" -o -z "$LEISURE_DIR" ]; then
    echo XUS_DIR and LEISURE_DIR must both be set
    exit 1
fi

if [ -n "$1" ]; then
    load="#load=$1"
else
    load='#load=local:///intro.lmd'
fi

dir=/home/bill/Insync/bill.burdick@gmail.com/LeisureStorage

page=local
#page=none
#page=deployed

case $page in
    local) url="-u http://localhost:\$XUS_PORT/leisure/drive.html${load}"
        ;;
    none) url="-w 9090"
        ;;
    deployed) url="-u http://zot.github.com/Leisure/drive.html${load}"
        ;;
esac

(cd "$XUS_DIR"; make && cp xus.js ~/lc/lambdaCalculus) && "$XUS_DIR/examples/leisure" start bubba $url -e leisureService -v "$@" --dir $dir -p
