// Generated by CoffeeScript 1.6.3
(function() {
  var exports;

  exports = module.exports;

  exports.d = function(obj) {
    return obj.constructor.name;
  };

  exports.log = function(str) {
    return console.log(str);
  };

}).call(this);

/*
//@ sourceMappingURL=base.map
*/
