// Generated by CoffeeScript 1.3.3
(function() {
  var exports, _;

  exports = module.exports = require('./base');

  require('./proto');

  require('./transport');

  _ = require('./lodash.min');

  if (window.MozWebSocket) {
    window.WebSocket = window.MozWebSocket;
  }

  exports.xusToProxy = function(xus, url) {
    var proxy, sock;
    proxy = new ProxyMux(function(con, batch) {
      return xus.processBatch(con, batch);
    });
    sock = new WebSocket(url);
    return sock.onopen = function() {
      return proxy.addPeerConnection(function(proxyCon) {
        return new WebSocketConnection(proxyCon, sock);
      });
    };
  };

}).call(this);
