// Generated by CoffeeScript 2.6.1
(function() {
  //###
  // Copyright (C) 2012, Bill Burdick
  // License: ZLIB license
  //###
  var ProxyMux, WebSocketConnection, _, exports, log;

  window.Xus = exports = module.exports = require('./base');

  require('./proto');

  ({log, ProxyMux, WebSocketConnection} = require('./transport'));

  require('./peer');

  window._ = _ = require('./lodash.min');

  if (window.MozWebSocket) {
    window.WebSocket = window.MozWebSocket;
  }

  exports.xusToProxy = function(xus, url, verbose) {
    var proxy, sock;
    proxy = new ProxyMux(xus);
    proxy.mainDisconnect = function(con) {
      console.log("Disconnecting mux connection and closing");
      window.open('', '_self', '');
      return window.close();
    };
    if (verbose != null) {
      proxy.verbose = log;
    }
    sock = new WebSocket(url);
    return sock.onopen = function() {
      return new WebSocketConnection(proxy, sock);
    };
  };

}).call(this);

//# sourceMappingURL=browser.js.map
