// Generated by CoffeeScript 1.6.3
(function() {
  var xus;

  xus = require('./peer');

  exports.main = function() {
    var peer;
    peer = xus.xusServer.createPeer(function(con) {
      return new xus.Peer(con);
    });
    peer.set('this/name', 'echo');
    return peer.listen('this/public/echo', true, function(key, value) {
      return console.log("***\n*** " + key + " = " + value + "\n***");
    });
  };

}).call(this);

/*
//@ sourceMappingURL=echo.map
*/
