// Generated by CoffeeScript 1.3.3
(function() {
  var xus;

  xus = require('./peer');

  module.exports.main = function(master) {
    var peer;
    peer = master.newPeer();
    return peer.set('this/links', ['leisure/storage']);
  };

}).call(this);
