// Generated by CoffeeScript 1.3.3
(function() {
  var Server, exports, modified;

  Server = (exports = require('./proto')).Server;

  require('./jquery.indexeddb');

  modified = false;

  Server.useIndexedDb = function(dbName, storeName, cont, err) {
    var dbPrm;
    if (!modified) {
      modified = true;
      console.log("initializing");
      window.db = dbPrm = $.indexedDB(dbName);
      console.log("1");
      dbPrm.done = function(d) {
        cont();
        return d;
      };
      dbPrm.fail = err || function() {};
      console.log("2");
      window.os = dbPrm.transaction(storeName, 1).objectStore(storeName);
      console.log("3");
      this.store = function(key, value) {
        return dbPrm.transaction(storeName, 1).objectStore(storeName).put(key, value);
      };
      return this.sendAll = function(con, path) {
        return dbPrm.transaction(storeName, 0).objectStore(storeName);
      };
    }
  };

}).call(this);
