#!/bin/bash

####
# Copyright (C) 2012, Bill Burdick
# License: ZLIB license
####

###
### You need to define these environment variables:
###   XUS_DIR -- the directory containing the Xus distro (parent of examples)
###   LEISURE_DIR -- the directory containing the Leisure distro
###   OPEN -- the path to chrome (defaults to /etc/alternatives/gnome-www-browser)
###   LEISURE_STORAGE -- directory to serve for leisure files (defaults to LEISURE_DIR)
###

LEISURE_STORAGE=${LEISURE_STORAGE:-$LEISURE_DIR}

usage() {
    cat <<EOF
$(basename $0) <name> <command> [<options>]

name is the name of the leisure instance

COMMANDS
start <name> [-v]         start the leisure instance, -v enables verbose
cat <name>                writes contents of current document
selecion <name>  [-a]     display the selection, -a means show whenever it changes
functions <name>          writes functions in current document
eval <name> <code>        evaluate code and return the result
repl <name> [-m]          read-eval-print-loop, -m makes the repl the master
files <name>              create file service and conneci to Leisure

Make sure you have defined the XUS_DIR and LEISURE_DIR (and maybe OPEN) environment variables.  See this script for details.
EOF
    exit 1
}

if [ -z "$XUS_DIR" -o -z "$LEISURE_DIR" ]; then
    usage
fi

OPEN="${OPEN:-/etc/alternatives/gnome-www-browser}"
#OPEN="${OPEN:-/etc/alternatives/gnome-www-browser} --always-enable-dev-tools"
XUS="$XUS_DIR/bin/xus"

evalResult() {
    expr="$1"
    if [ -z "$expr" ]; then
        exit
    fi
    while [ $(echo "$expr" | jshon -l) != 0 ]; do
        echo $(echo "$expr" | jshon -e 0 -e 2 -u)
        expr="$(echo "$expr" | jshon -d 0)"
    done
}

case "$1" in
start)
        name="$2"
        shift 2
        verbose=""
        addr=""
        #url="doc.html"
        url="drive.html"
        size=""
        requirements=""
        while true; do
            case "$1" in
                -v)
                    verbose="-v"
                    shift
                    ;;
                -w)
                    addr="-w $2"
                    shift 2
                    ;;
                -u)
                    pre="$OPEN"'$size '
                    if expr "$2" : ".*:.*"; then
                        app='--app='$2
                    else
                        app='--app=http://localhost:$XUS_PORT/leisure/'$2
                    fi
                    if expr "$app" : ".*#.*"; then
                        cmd=${pre}'"'$app'&xusproxy=ws://localhost:$XUS_PORT/proxy"'
                    else
                        cmd=${pre}'"'$app'#xusproxy=ws://localhost:$XUS_PORT/proxy"'
                    fi
                    echo COMMAND: $cmd
                    shift 2
                    ;;
                -s)
                    size=" --app-window-size=$2 "
                    shift 2
                    ;;
                -e)
                    requirements=" -e $2 $requirements"
                    shift 2
                    ;;
                *)
                    extra="$*"
                    break
                    ;;
            esac
        done
        echo URL: $url, extra: $extra
        $XUS start "$name" $verbose $addr $requirements -p -u '/leisure' $LEISURE_DIR -u /storage "$LEISURE_STORAGE" -x "$cmd" $extra
;;
cat)
        echo -E "[$($XUS get $2 leisure/document | sed -e 's/[^ ]* //')]" | jshon -e 0 -u
;;
functions)
        $XUS get $2 -v leisure/functions | jshon -a -u
;;
selection)
        if [ "$3"  = -a ]; then
            $XUS listen $2 leisure/selection/contents | sed -e 's/^[^ ]*\( \|$\)//'
        else
            sel="$($XUS get $2 -v leisure/selection/contents)"
            if [ -n "$sel" ]; then
                echo "[$sel]" | jshon -e 0 -u
            fi
        fi
;;
eval)
        $XUS run $2 $0 eval-cmd "$3"
;;
eval-cmd)
        shift
        result="peer/$XUS_PEER/public/exprResult"
        echo '[["set", "peer/'$XUS_PEER'/listen", ["'$result'"]],["set", "leisure/evalExpr", ["'"$*"'", "'$result'"]]]' >&4
        read -r line <&3
        if [ "$(echo $line | jshon -l)" != 1 ]; then
            evalResult "$(echo $line | jshon -d 0)"
        else
            read -r line <&3
            evalResult "$line"
        fi
;;
repl)
        name=$2
        shift 2
        $XUS run $name $0 repl-cmd "$@"
;;
repl-cmd)
        if [ "$2" = -m ]; then
            master='["set", "peer/'$XUS_PEER'/master", true],'
            shift
        else
            master=""
        fi
        result="peer/$XUS_PEER/public/exprResult"
        echo '['$master'["set", "peer/'$XUS_PEER'/listen", ["'$result'"]]]' >&4
        read -r line <&3
        while true; do
            read -p "Leisure> " -e input
            echo '[["set", "leisure/evalExpr", ["'"$input"'", "'$result'"]]]' >&4
            read -r line <&3
            evalResult "$line"
        done
;;
files)
        name=$2
        shift 2
        $XUS run $name $0 files-cmd "$@"
;;
files-cmd)
        if [ "$2" = -m ]; then
            master='["set", "peer/'$XUS_PEER'/master", true],'
            shift
        else
            master=""
        fi
        echo '['$master'["set", "peer/'$XUS_PEER'/listen", ["'$result'"]]]' >&4
;;
*) usage
;;
esac
