#!/bin/bash

####
# Copyright (C) 2012, Bill Burdick
# License: ZLIB license
####

if [ $# != 1 ]; then
    echo usage: $(basename $0) key
    exit 1
fi

key="$1"
echo '[["set", "this/listen", ["'$key'"]]]' >&4
read line <&3
line="$(echo $line | jshon -e 0 -d 0 -d 0 -d 0 -d 0)"
while [ "$(echo $line | jshon -l)" -gt 0 ]; do
    set $(echo $line | jshon -e 0 -u -p -e 1)
    echo $1 = $2
    line="$(echo $line | jshon -d 0 -d 0)"
done
while true; do
    read line <&3
    if [ "$line" = "" ]; then
        exit
    fi
    while [ $(echo $line | jshon -l) != 0 ]; do
        set $(echo $line | jshon -e 0 -e 0 -u -p -e 1 -u -p -e 2)
        extra=""
        if [ "$(echo $line | jshon -e 0 -l)" -gt 3 ]; then extra="$(echo $line | jshon -e 0 -e 3)"; fi
        echo $1 $2 $3 $extra
        line="$(echo $line | jshon -d 0)"
    done
done
